"""Multidimensional phase unwrapping as a cycle-constrained flow.

The grid and the loops
----------------------
A wrapped phase field is known only modulo one turn, so unwrapping a grid means
choosing, for every pair of neighbours, the whole number of turns ``k`` to add
to the wrapped step between them.  What makes the choice meaningful is that the
corrected steps have to be the steps of one single valued field: walking around
any closed loop of the grid must come back to the starting value, so the
corrected steps of a loop add up to zero.  Counting in turns, that is

    sum(sign * k) = -r(C)     for every loop C,

where ``sign`` is the direction in which the loop walks each of its edges and
``r(C)`` is the residue of the loop, the whole number of turns of error the
wrapped field carries around it.  The residue of a loop is a closed loop
invariant of the wrapped field, and it is the quantity the classical methods
work with (Goldstein, Zebker and Werner 1988; Ghiglia and Pritt 1998, ch. 4).

The elementary squares are enough.  The cycle space of a grid is generated by
its elementary squares, so the constraints of the squares imply the constraint
of every loop, and Parvaneh builds one cycle per square.  A two dimensional
``R`` by ``C`` grid has ``(R - 1) * (C - 1)`` of them and a three dimensional
``n`` cube has ``3 * n * (n - 1) ** 2``; :func:`grid_cycles` returns exactly
those.

Why the third dimension changes the problem
-------------------------------------------
In two dimensions every edge belongs to at most two squares, and the
square/arc incidence matrix is then the vertex/arc incidence matrix of a
network.  A minimum cost flow therefore minimises the cost over all integer
flows that close every square, exactly and in polynomial time: that is
Costantini's method (Costantini 1998), which :mod:`parvaneh.network_flow`
implements.

A third axis breaks that argument.  An interior edge of a three dimensional
grid belongs to four squares, some edges belong to two squares that walk them
in the *same* direction, and the incidence matrix is no longer a network
matrix.  The formulation becomes a minimum cost circulation over a general
integer matrix, which is NP-hard (Chen and Zebker 2002, section IV, where the
argument is made for the general network model).  The failure is structural
rather than incidental: :func:`parvaneh.graph_flow.build_dual_network` refuses
a pair of squares that walk an edge the same way, and a volume always contains
one, because the edge that leaves a corner along the first axis is walked
forwards by the square in each of the other two planes.  There is therefore no
volume, however small, that the two dimensional network can solve as it stands.
Three dimensional formulations published since then keep the flow machinery but
add an outer search or a relaxation (Liu and Pan 2020, whose "closure phase" is
the loop residue ``r(C)`` of the equation above).

This module therefore exposes three ways to deal with a volume:

``"flow"``
    the two dimensional dual network of :mod:`parvaneh.graph_flow`, exact and
    polynomial, available whenever the grid has two axes.
``"ilp"``
    the same squares solved exactly by linear relaxation and branch and bound.
    One relaxation is a linear program with one row per square and two
    nonnegative columns per edge, so the work grows quickly with the size of
    the volume; ``max_nodes`` bounds the number of relaxations and
    :class:`FlowNDInfo` reports whether the search finished.
``"slice"``
    unwrap every plane of a stack on its own and leave the edges that cross
    planes alone.  It is the baseline the volumetric solve is meant to be
    compared with, and the only one of the three that scales to a real stack.

``"auto"`` uses ``"flow"`` where it exists and ``"ilp"`` otherwise, and on a
volume the exact search is seeded with the planes' answer.  That answer is a
good guess rather than a promise: the squares of a volume mix edges inside a
plane with edges that cross planes, and the planes' jumps leave the crossing
ones at zero, so the guess closes every square only sometimes.  It is used when
it does and dropped when it does not, and :attr:`FlowNDInfo.seeded` says which
happened.  Either way the answer is a field that closes every square.

Costs, gauge and comparison
---------------------------
The default cost is the weighted total variation ``sum(w * abs(k))``, the
objective of Costantini's method, with ``w`` the smaller confidence of the two
samples of an edge.  ``cost="quadratic"`` minimises ``sum(w * k ** 2)``
instead, which spreads the correction over the field rather than concentrating
it; it is available only where the structure is a network, because the exact
solver needs a linear objective.

Integration is a spanning forest walk over the samples whose confidence is
positive, and it is path independent because the jumps make the corrected field
close every square.  The additive constant of each connected component is the
one thing the data cannot fix; ``align`` decides how to pin it down and the
default follows :mod:`parvaneh.network_flow`.  The unwrapped field is congruent
to the wrapped one sample by sample, ``wrap(result) == wrap(phase)``, up to
floating point rounding of the whole turn offsets.

The planes of a stack are solved with the same engine and the same cost as the
volume, so the only difference between ``"slice"`` and ``"ilp"`` is the
constraint set, which is what a comparison of two dimensional and three
dimensional unwrapping needs.  Both report the same ``total_variation``, so the
two can be put side by side.

Scale
-----
The exact volume solve is meant for small volumes.  The number of rows of every
relaxation is the number of squares and the number of columns is twice the
number of edges.

==========  =============  =============
volume      squares        edges
==========  =============  =============
``8^3``     1176           1344
``16^3``    10800          11520
``32^3``    92256          95232
``64^3``    762048         774144
==========  =============  =============

Building the squares is a Python loop over them, and
:func:`parvaneh.graph_flow.residues_of_cycles` is a Python loop as well, so
both cost time proportional to the number of squares with a large constant: a
``64^3`` volume is hundreds of thousands of iterations before the first
relaxation is even solved.  The integration walk is a Python loop over the
samples.  Nothing here is written for speed.  It is a reference implementation
whose answers the faster paths can be checked against.

References
----------
M. Costantini, "A novel phase unwrapping method based on network programming,"
*IEEE Transactions on Geoscience and Remote Sensing* 36(3) (1998) 813-821.

C. W. Chen and H. A. Zebker, "Phase unwrapping for large SAR interferograms:
statistical segmentation and generalized network models," *IEEE Transactions on
Geoscience and Remote Sensing* 40(8) (2002) 1709-1719.

F. Liu and B. Pan, "A new 3-D minimum cost flow phase unwrapping algorithm
based on closure phase," *IEEE Transactions on Geoscience and Remote Sensing*
58(3) (2020) 1857-1867.

J. M. Bioucas-Dias and G. Valadao, "Phase unwrapping via graph cuts," *IEEE
Transactions on Image Processing* 16(3) (2007) 698-709.

R. M. Goldstein, H. A. Zebker and C. L. Werner, "Satellite radar
interferometry: two-dimensional phase unwrapping," *Radio Science* 23(4)
(1988) 713-720.

D. C. Ghiglia and M. D. Pritt, *Two-Dimensional Phase Unwrapping: Theory,
Algorithms and Software*, Wiley, 1998.
"""

from dataclasses import dataclass

import numpy as np

from . import graph_flow
from .core import _axis_slice, _wrap
from .reliability import _axis_confidence, _check_phase, _confidence

_TWO_PI = 2.0 * np.pi

#: Solvers accepted by :func:`flow_nd_unwrap`.
METHODS = ("auto", "flow", "ilp", "slice")

#: Cost functions accepted by :func:`flow_nd_unwrap`.
COST_MODES = ("linear", "quadratic")

#: Gauge conventions accepted by :func:`flow_nd_unwrap`.
ALIGN_MODES = ("zero", "mean", "median")


@dataclass
class FlowNDInfo:
    """Bookkeeping for one multidimensional flow solve.

    ``backend`` names the engine that produced the answer: ``"grid-network"``
    is the minimum cost flow of the dual network, ``"grid-branch-bound"`` is
    the exact solver of :mod:`parvaneh.graph_flow`, and ``"grid-slice"`` is the
    plane by plane baseline.

    ``nodes``, ``edges`` and ``pixels`` always describe the whole grid of the
    input array.  ``cycles`` and ``residues`` describe the squares that were
    really used, so for ``"grid-slice"`` they are summed over the planes and
    for the other backends they count every square of the volume.
    ``augmentations``, ``relaxations`` and ``proven`` belong to the solver that
    ran; ``seeded`` records whether the exact search accepted the planes'
    answer as its first incumbent.  ``objective`` is what the solver minimised
    and ``total_variation`` is the weighted total variation
    ``sum(weight * abs(jump))`` of the answer, which is reported for every
    backend so the cost modes can be compared on equal terms.

    ``slices`` is the number of planes solved on their own and is zero for the
    backends that solve the volume in one piece.  ``max_jump`` is the largest
    whole turn correction any single edge received, and ``components`` is the
    number of connected groups of usable samples the field was integrated on.
    """

    backend: str
    method: str
    cost: str
    shape: tuple
    pixels: int
    nodes: int
    edges: int
    cycles: int
    residues: int
    components: int
    max_jump: int
    objective: float
    total_variation: float
    augmentations: int
    relaxations: int
    proven: bool
    seeded: bool
    slices: int


def _edge_shapes(shape):
    """Shape of the jump array of every axis, that is, of ``diff`` along it."""
    return tuple(shape[:axis] + (shape[axis] - 1,) + shape[axis + 1:]
                 for axis in range(len(shape)))


def _flat_jumps(jumps):
    """Stack per-axis jump arrays into the edge order of :func:`grid_edges`."""
    return np.concatenate([np.asarray(jump, dtype=np.int64).ravel()
                           for jump in jumps])


def grid_edges(shape):
    """Enumerate the edges of a grid graph, axis by axis and in C order.

    Every edge is oriented from the sample with the smaller index along its
    axis to the sample with the larger one, so the edge of axis ``a`` joining
    the samples at ``p`` and ``p + stride(a)`` is listed once.

    Parameters
    ----------
    shape : sequence of int
        Shape of the grid.

    Returns
    -------
    numpy.ndarray
        Index of every vertex, as an array of the grid shape.
    numpy.ndarray
        Tail of every edge.
    numpy.ndarray
        Head of every edge.

    Raises
    ------
    ValueError
        If the grid has fewer than two axes or an axis without a sample.
    """
    shape = tuple(int(size) for size in shape)
    if len(shape) < 2:
        raise ValueError("a grid needs at least two axes")
    if min(shape) < 1:
        raise ValueError("every axis of a grid needs at least one vertex")
    nodes = np.arange(int(np.prod(shape)), dtype=np.int64).reshape(shape)
    tail, head = [], []
    for axis in range(len(shape)):
        source = _axis_slice(nodes, axis, slice(0, -1))
        sink = _axis_slice(nodes, axis, slice(1, None))
        tail.append(np.ascontiguousarray(source).ravel())
        head.append(np.ascontiguousarray(sink).ravel())
    return nodes, np.concatenate(tail), np.concatenate(head)


def grid_edge_index(shape):
    """Number the edges of a grid the way :func:`grid_edges` lists them.

    Parameters
    ----------
    shape : sequence of int
        Shape of the grid.

    Returns
    -------
    tuple of numpy.ndarray
        One array per axis, shaped like the edges of that axis, holding the
        position of each edge in the flat list of :func:`grid_edges`.  The
        arrays describe the edges only rather than the whole grid, so they stay
        small.  An element of one axis' array stands for the same corner of the
        grid as the element in the same position of another axis' array, which
        is what :func:`grid_cycles` relies on.

    Raises
    ------
    ValueError
        If the grid has fewer than two axes or an axis without a sample.
    """
    shape = tuple(int(size) for size in shape)
    if len(shape) < 2:
        raise ValueError("a grid needs at least two axes")
    if min(shape) < 1:
        raise ValueError("every axis of a grid needs at least one vertex")
    index, offset = [], 0
    for axis in range(len(shape)):
        edge_shape = shape[:axis] + (shape[axis] - 1,) + shape[axis + 1:]
        size = int(np.prod(edge_shape))
        index.append(np.arange(offset, offset + size,
                               dtype=np.int64).reshape(edge_shape))
        offset += size
    return tuple(index)


def grid_cycles(shape, index):
    """Enumerate the elementary squares of a grid.

    One square is produced for every pair of axes and every vertex that has a
    neighbour along both of them, so a two dimensional ``R`` by ``C`` grid has
    ``(R - 1) * (C - 1)`` squares and a three dimensional ``n`` cube has
    ``3 * n * (n - 1) ** 2``.  The square leaves the corner along the first axis,
    comes back along the second, returns along the first against its own
    direction and closes along the second, so its signs are ``+1, +1, -1, -1``
    in that order.

    Parameters
    ----------
    shape : sequence of int
        Shape of the grid.
    index : sequence of numpy.ndarray
        Edge numbering of :func:`grid_edge_index`.

    Returns
    -------
    list of tuple of numpy.ndarray
        Squares as ``(edge indices, signs)``.  The signs are one shared read
        only array and every edge array is a read only view of a corner kernel,
        so the whole set costs little more than the numbering itself.

    Notes
    -----
    For a pair of axes the corner kernel holds, at every corner, the edge that
    leaves it along the first axis, the edge that leaves the corner one step
    further along the second axis along that same axis, the edge of the first
    axis at that further corner, and the edge of the second axis that leaves
    the corner itself.  The four columns are built by cutting views of the two
    edge numberings, and they line up element by element because each cut is
    taken over the same corner grid.
    """
    signs = np.array([1, 1, -1, -1], dtype=np.int64)
    signs.flags.writeable = False
    cycles = []
    for first in range(len(shape)):
        for second in range(first + 1, len(shape)):
            along = index[first]
            across = index[second]
            kernel = np.stack(
                [_axis_slice(along, second, slice(0, -1)).ravel(),
                 _axis_slice(across, first, slice(1, None)).ravel(),
                 _axis_slice(along, second, slice(1, None)).ravel(),
                 _axis_slice(across, first, slice(0, -1)).ravel()], axis=1)
            kernel.flags.writeable = False
            for row in range(kernel.shape[0]):
                cycles.append((kernel[row], signs))
    return cycles


def corrected_gradients(phase, jumps):
    """Apply whole turn jumps to the wrapped gradients of a grid.

    The corrected step of an edge is ``wrap(step) + 2 pi * k``, which is the
    step the unwrapped field has when the raw step needed ``k`` turns removed
    from it.

    Parameters
    ----------
    phase : array_like of float
        Wrapped phase in radians.
    jumps : sequence of array_like of int
        Whole turns per axis, shaped like ``numpy.diff(phase, axis=axis)``.

    Returns
    -------
    list of numpy.ndarray
        Corrected step of every axis.

    Raises
    ------
    ValueError
        If there is not one jump array per axis, or if one of them does not
        match the gradients of its axis.
    """
    jumps = list(jumps)
    if len(jumps) != phase.ndim:
        raise ValueError("one jump array per axis is required")
    corrected = []
    for axis in range(phase.ndim):
        step = _wrap(np.diff(phase, axis=axis))
        jump = np.asarray(jumps[axis], dtype=np.int64)
        if jump.shape != step.shape:
            raise ValueError("the jump of axis %d does not match the grid"
                             % axis)
        corrected.append(step + _TWO_PI * jump)
    return corrected


def jumps_from_field(phase, field):
    """Whole turn jumps that turn ``phase`` into ``field``.

    The result is the number of turns removed from every raw step of ``phase``
    to obtain the matching step of ``field``.  It telescopes around every loop,
    so the jumps of any finite field close every square, which is the quickest
    way to check a field for closure.  Non-finite steps, which a masked field
    produces, are reported as no turn at all.

    Parameters
    ----------
    phase, field : array_like of float
        Wrapped phase and the field to compare it with, of equal shape.

    Returns
    -------
    list of numpy.ndarray
        Whole turns per axis, as integers.

    Raises
    ------
    ValueError
        If the two arrays do not have the same shape.
    """
    field = np.asarray(field, dtype=np.float64)
    if field.shape != phase.shape:
        raise ValueError("the field must have the shape of the phase")
    jumps = []
    for axis in range(phase.ndim):
        step = np.diff(field, axis=axis) - _wrap(np.diff(phase, axis=axis))
        turns = np.rint(step / _TWO_PI)
        turns = np.where(np.isfinite(turns), turns, 0.0)
        jumps.append(turns.astype(np.int64))
    return jumps


def solve_grid_flow(phase, confidence, *, cost="linear", method="auto",
                    max_iter=None, max_nodes=None, initial=None):
    """Close every square of a grid at the least cost.

    Parameters
    ----------
    phase : array_like of float
        Wrapped phase in radians.
    confidence : array_like of float
        Per-sample confidence; the weight of an edge is the smaller confidence
        of its two samples, so an edge that touches an unusable sample is free.
    cost : {"linear", "quadratic"}, optional
        Objective of the solve, see the module docstring.
    method : {"auto", "flow", "ilp"}, optional
        Solver, see the module docstring.
    max_iter : int, optional
        Augmentation limit of the network solver.
    max_nodes : int, optional
        Relaxation limit of the exact solver.
    initial : array_like of int, optional
        Feasible flow offered to the exact solver as its first incumbent, in
        the edge order of :func:`grid_edges`.  It is discarded when it does not
        close every square, so an invalid guess costs time and never
        correctness.

    Returns
    -------
    list of numpy.ndarray
        Whole turns of every axis.
    parvaneh.graph_flow.FlowInfo
        Bookkeeping of the flow solve.
    dict
        ``total_variation``, the weighted total variation of the answer, and
        ``max_jump``, its largest entry.

    Raises
    ------
    ValueError
        If an option is unknown, or if the grid is not a network and
        ``cost="quadratic"`` was asked for.
    """
    if method not in ("auto", "flow", "ilp"):
        raise ValueError("method must be 'auto', 'flow' or 'ilp'")
    if cost not in COST_MODES:
        raise ValueError("cost must be one of %s" % (COST_MODES,))
    shape = phase.shape
    nodes, tail, head = grid_edges(shape)
    cycles = grid_cycles(shape, grid_edge_index(shape))
    gradients, weights = [], []
    for axis in range(phase.ndim):
        gradients.append(_wrap(np.diff(phase, axis=axis)).ravel())
        weights.append(_axis_confidence(confidence, axis).ravel())
    gradients = np.concatenate(gradients)
    weights = np.concatenate(weights)
    if cost == "linear":
        arc_cost = graph_flow.LinearCost(weights)
    else:
        arc_cost = graph_flow.QuadraticCost(weights, np.zeros_like(weights))
    flow, info = graph_flow.curl_flow(int(nodes.size), tail, head, gradients,
                                      cost=arc_cost, cycles=cycles,
                                      method=method, max_iter=max_iter,
                                      max_nodes=max_nodes, initial=initial,
                                      return_info=True)
    shapes = _edge_shapes(shape)
    jumps, offset = [], 0
    for axis in range(phase.ndim):
        size = int(np.prod(shapes[axis]))
        jumps.append(flow[offset:offset + size].reshape(shapes[axis]))
        offset += size
    stats = {"total_variation": float(np.sum(weights * np.abs(flow))),
             "max_jump": int(np.abs(flow).max()) if flow.size else 0}
    return jumps, info, stats


def integrate_edges(phase, confidence, jumps, *, align="zero"):
    """Integrate corrected gradients into one unwrapped field.

    The grid is walked with a spanning forest.  The result does not depend on
    the order of the walk, because the jumps make the corrected field close
    every square and a loop that closes can be crossed in either direction.
    Samples whose confidence is zero come back as ``NaN``.

    Parameters
    ----------
    phase : array_like of float
        Wrapped phase in radians.
    confidence : array_like of float
        Per-sample confidence.
    jumps : sequence of array_like of int
        Whole turns per axis.
    align : {"zero", "mean", "median"}, optional
        How to fix the additive constant of every connected component.  A
        component is known only up to a whole number of turns.  ``"zero"``
        keeps the wrapped value of its first sample in raster order, which is
        what :mod:`parvaneh.network_flow` does.  ``"mean"`` and ``"median"``
        instead remove the whole number of turns closest to the average or the
        median turned difference between the field and the input phase, which
        cancels the offset that unwrapping every plane of a stack on its own
        leaves behind.  Neither choice can recover a genuine offset of many
        turns, so this is a gauge convention and not a measurement.

    Returns
    -------
    numpy.ndarray
        Unwrapped field.
    numpy.ndarray
        Component label of every sample, ``-1`` where the confidence is zero.

    Raises
    ------
    ValueError
        If ``align`` is unknown.
    """
    if align not in ALIGN_MODES:
        raise ValueError("align must be one of %s" % (ALIGN_MODES,))
    shape = phase.shape
    nodes, tail, head = grid_edges(shape)
    values = np.concatenate(
        [array.ravel() for array in corrected_gradients(phase, jumps)])
    source = np.concatenate([tail, head])
    target = np.concatenate([head, tail])
    value = np.concatenate([values, -values])
    order = np.argsort(source, kind="stable")
    starts = np.searchsorted(source[order], np.arange(nodes.size + 1))
    flat_phase = phase.ravel()
    valid = confidence.ravel() > 0.0
    result = np.full(nodes.size, np.nan)
    labels = np.full(nodes.size, -1, dtype=np.int64)
    components = 0
    for root in range(nodes.size):
        if not valid[root] or labels[root] >= 0:
            continue
        labels[root] = components
        result[root] = flat_phase[root]
        stack = [root]
        members = [root]
        while stack:
            node = stack.pop()
            here = result[node]
            for slot in range(int(starts[node]), int(starts[node + 1])):
                edge = int(order[slot])
                neighbour = int(target[edge])
                if labels[neighbour] >= 0 or not valid[neighbour]:
                    continue
                labels[neighbour] = components
                result[neighbour] = here + value[edge]
                stack.append(neighbour)
                members.append(neighbour)
        if align != "zero":
            turns = (result[members] - flat_phase[members]) / _TWO_PI
            offset = np.median(turns) if align == "median" else np.mean(turns)
            result[members] -= _TWO_PI * np.rint(offset)
        components += 1
    return result.reshape(shape), labels.reshape(shape)


def _slice_jumps(phase, confidence, *, slice_axis=0, max_iter=None):
    """Unwrap every plane of a stack on its own.

    The planes go through the same engine and the same cost as the volumetric
    solve, so the two differ only in their constraints.  Edges that cross
    planes keep a jump of zero.

    Parameters
    ----------
    phase : array_like of float
        Wrapped phase with three axes.
    confidence : array_like of float
        Per-sample confidence.
    slice_axis : int, optional
        Axis along which the stack is cut.
    max_iter : int, optional
        Augmentation limit of the network solver.

    Returns
    -------
    list of numpy.ndarray
        Whole turns of every axis of the stack.
    dict
        The cycle, residue, augmentation, objective, total variation and
        maximum jump totals of the planes, and the number of planes.

    Raises
    ------
    ValueError
        If the phase does not have three axes.
    """
    if phase.ndim != 3:
        raise ValueError("the slice baseline is defined for three dimensions")
    order = [axis for axis in range(3) if axis != slice_axis]
    planes = np.moveaxis(phase, slice_axis, 0)
    weights = np.moveaxis(confidence, slice_axis, 0)
    jumps = [np.zeros(shape, dtype=np.int64)
             for shape in _edge_shapes(phase.shape)]
    summary = {"slices": int(planes.shape[0]), "cycles": 0, "residues": 0,
               "augmentations": 0, "objective": 0.0, "total_variation": 0.0,
               "max_jump": 0}
    for plane in range(planes.shape[0]):
        piece, info, stats = solve_grid_flow(planes[plane], weights[plane],
                                             cost="linear", method="flow",
                                             max_iter=max_iter)
        for slot, axis in enumerate(order):
            _axis_slice(jumps[axis], slice_axis, plane)[...] = piece[slot]
        summary["cycles"] += int(info.cycles)
        summary["residues"] += int(info.residues)
        summary["augmentations"] += int(info.augmentations)
        summary["objective"] += float(info.objective)
        summary["total_variation"] += float(stats["total_variation"])
        summary["max_jump"] = max(summary["max_jump"], stats["max_jump"])
    return jumps, summary


def flow_nd_unwrap(phase, weight=None, mask=None, *, method="auto",
                   cost="linear", align="zero", slice_axis=0, max_iter=None,
                   max_nodes=None, return_info=False):
    """Unwrap a two or three dimensional phase field by closing every square.

    Parameters
    ----------
    phase : array_like of float
        Wrapped phase in radians, with at least two axes and at least two
        samples along every axis.
    weight : array_like of float, optional
        Nonnegative per-sample confidence; zero removes a sample.
    mask : array_like of bool, optional
        Samples to use, combined with ``weight`` the way
        :func:`parvaneh.reliability.pixel_reliability` combines them.
    method : {"auto", "flow", "ilp", "slice"}, optional
        Solver, see the module docstring.  ``"slice"`` reduces a three
        dimensional array to independent planes and is the baseline the exact
        volume solve is compared with.
    cost : {"linear", "quadratic"}, optional
        Objective, see the module docstring.
    align : {"zero", "mean", "median"}, optional
        Gauge of every connected component, see :func:`integrate_edges`.
    slice_axis : int, optional
        Axis along which ``"slice"`` cuts the stack.
    max_iter : int, optional
        Augmentation limit of the network solver.
    max_nodes : int, optional
        Relaxation limit of the exact solver.  When the search stops early the
        best flow found so far is returned and ``info.proven`` is false, so the
        answer is always a field that closes every square, but not always the
        cheapest one.
    return_info : bool, optional
        Also return a :class:`FlowNDInfo`.

    Returns
    -------
    numpy.ndarray
        Unwrapped field, ``NaN`` where the confidence is zero.
    FlowNDInfo
        Only when ``return_info`` is true.

    Raises
    ------
    ValueError
        If the phase is not finite, if an axis is shorter than two samples, if
        an option is unknown, or if ``"flow"`` is asked for a structure that is
        not a network, which is the case as soon as there is a third axis.
    RuntimeError
        If the exact solver found no integer flow within ``max_nodes``
        relaxations.

    Examples
    --------
    A volume is unwrapped as one problem, and the same volume is unwrapped
    plane by plane to see what the third axis is worth:

    >>> volume = ...                                    # doctest: +SKIP
    >>> joint = flow_nd_unwrap(volume, method="ilp")     # doctest: +SKIP
    >>> baseline = flow_nd_unwrap(volume, method="slice")  # doctest: +SKIP
    """
    array = _check_phase(phase)
    if array.ndim < 2:
        raise ValueError("flow_nd_unwrap needs at least two dimensions")
    if method not in METHODS:
        raise ValueError("method must be one of %s" % (METHODS,))
    if cost not in COST_MODES:
        raise ValueError("cost must be one of %s" % (COST_MODES,))
    if align not in ALIGN_MODES:
        raise ValueError("align must be one of %s" % (ALIGN_MODES,))
    if not 0 <= slice_axis < array.ndim:
        raise ValueError("slice_axis is out of range")
    if method == "slice" and array.ndim != 3:
        raise ValueError("method 'slice' is defined for three dimensions")
    confidence = _confidence(array, mask, weight)
    jumps = None
    summary = {"slices": 0, "cycles": 0, "residues": 0, "augmentations": 0,
               "objective": 0.0, "total_variation": 0.0, "max_jump": 0}
    if array.ndim >= 3 and method in ("auto", "ilp", "slice"):
        jumps, summary = _slice_jumps(array, confidence,
                                      slice_axis=slice_axis,
                                      max_iter=max_iter)
    if method == "slice":
        backend = "grid-slice"
        relaxations, proven, seeded = 0, True, False
    else:
        seed = None if jumps is None else _flat_jumps(jumps)
        jumps, flow, solved = solve_grid_flow(array, confidence, cost=cost,
                                              method=method,
                                              max_iter=max_iter,
                                              max_nodes=max_nodes,
                                              initial=seed)
        backend = ("grid-network" if flow.method == "flow"
                   else "grid-branch-bound")
        relaxations = int(flow.relaxations)
        proven = bool(flow.proven)
        seeded = bool(flow.seeded)
        summary = {"slices": 0, "cycles": int(flow.cycles),
                   "residues": int(flow.residues),
                   "augmentations": int(flow.augmentations),
                   "objective": float(flow.objective),
                   "total_variation": solved["total_variation"],
                   "max_jump": solved["max_jump"]}
    result, labels = integrate_edges(array, confidence, jumps, align=align)
    if not return_info:
        return result
    info = FlowNDInfo(backend=backend, method=method, cost=cost,
                      shape=array.shape,
                      pixels=int(np.count_nonzero(confidence > 0.0)),
                      nodes=int(array.size),
                      edges=int(sum(int(np.prod(size))
                                    for size in _edge_shapes(array.shape))),
                      cycles=int(summary["cycles"]),
                      residues=int(summary["residues"]),
                      components=int(labels.max()) + 1,
                      max_jump=int(summary["max_jump"]),
                      objective=float(summary["objective"]),
                      total_variation=float(summary["total_variation"]),
                      augmentations=int(summary["augmentations"]),
                      relaxations=relaxations, proven=proven, seeded=seeded,
                      slices=int(summary["slices"]))
    return result, info
